### PR TITLE
Fix json object instead of array

### PR DESCRIPTION
**Pull request by MisterDuval**
json property and getJson method are object not array

### CODE REVIEW

**Review by fpalamour — APPROVED** [review]

**Comment by fpalamour** [comment]
Do you think more PRs are to come or can I already create a new release ?

**Comment by ogizanagi** [comment]
Would be ok for a new release on my-side. No more issue to report

**Comment by MisterDuval** [comment]
Go for a new release!

**Comment by fpalamour** [comment]
New release v1.0.5 is available !

**Pull request merged**
